version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
      build: .
      ports:
        - "5002:5002"
      volumes:
        - .:/code
      depends_on:
        - redis
